"use client";
import { createContext, useCallback, useContext, useEffect, useState } from 'react';
import { Account, Activity, Database, Profile, Workspace, blankProfile, emptyDatabase, emptyWorkspace } from '@/lib/research-model';
import { repository, storageKey } from '@/services/repositories/localRepository';
type Store = { db: Database; workspace: Workspace; account?: Account; ready: boolean; error: string; notice: string; dismiss:()=>void; transact:(fn:(db:Database)=>void)=>void; mutate:(fn:(w:Workspace)=>void,action?:string,object?:string,projectId?:string,href?:string)=>void; signup:(name:string,email:string,password:string)=>Promise<void>; login:(email:string,password:string)=>Promise<void>; logout:()=>void; updateProfile:(changes:Partial<Profile>)=>void; startDemo:()=>Promise<void>; resetPassword:(email:string,token:string,password:string)=>Promise<void>; requestReset:(email:string)=>string; };
const Context = createContext<Store|null>(null);
async function hashPassword(password:string,salt:string) { const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(bits),v=>v.toString(16).padStart(2,'0')).join(''); }
export function validatePassword(password:string) { if(password.length<10 || !/[a-z]/i.test(password) || !/\d/.test(password)) throw new Error('Use at least 10 characters, including a letter and a number.'); }
export function WorkspaceProvider({children}:{children:React.ReactNode}) {
 const [db,setDb]=useState<Database>(emptyDatabase),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{const load=()=>{try{setDb(repository.read());setError('');}catch(e){setError((e as Error).message);}setReady(true);};const timer=setTimeout(load,0);const sync=(e:StorageEvent)=>{if(e.key===storageKey)load();};window.addEventListener('storage',sync);return()=>{clearTimeout(timer);window.removeEventListener('storage',sync);};},[]);
 const transact=useCallback((fn:(data:Database)=>void)=>{try{const next=structuredClone(repository.read());fn(next);next.revision++;repository.write(next);setDb(next);setError('');}catch(e){const message=(e as Error).message||'Browser storage is unavailable. Your change was not saved.';setError(message);throw new Error(message);}},[]);
 const mutate=useCallback((fn:(w:Workspace)=>void,action?:string,object='',projectId='',href='/activity')=>{transact(next=>{if(!next.session||!next.workspaces[next.session])throw new Error('Log in to continue.');const w=next.workspaces[next.session];fn(w);if(action){const event:Activity={id:crypto.randomUUID(),action,object,projectId,href,createdAt:new Date().toISOString(),read:false};w.activity.unshift(event);if(action.includes('AI')?w.settings.aiNotifications:w.settings.activityNotifications)w.notifications.unshift(event);}});if(action)setNotice(`${action}${object?`: ${object}`:''}. Saved on this device.`);},[transact]);
 const signup=async(name:string,email:string,password:string)=>{validatePassword(password);email=email.trim().toLowerCase();if(!name.trim()||!/^\S+@\S+\.\S+$/.test(email))throw new Error('Enter your name and a valid email address.');const salt=crypto.randomUUID(),passwordHash=await hashPassword(password,salt),id=crypto.randomUUID();transact(next=>{if(next.accounts.some(a=>a.profile.email===email))throw new Error('An account with this email already exists on this device.');next.accounts.push({id,salt,passwordHash,profile:blankProfile(name.trim(),email)});next.workspaces[id]=emptyWorkspace();next.session=id;});mutate(()=>{},'Signed up',name);};
 const login=async(email:string,password:string)=>{const a=repository.read().accounts.find(a=>a.profile.email===email.trim().toLowerCase());if(!a||await hashPassword(password,a.salt)!==a.passwordHash)throw new Error('Email or password is incorrect for this device.');transact(next=>{next.session=a.id;});mutate(()=>{},'Logged in',a.profile.name);};
 const logout=()=>transact(next=>{next.session=null;});
 const updateProfile=(changes:Partial<Profile>)=>{transact(next=>{const a=next.accounts.find(a=>a.id===next.session);if(!a)throw new Error('Log in to continue.');if(changes.email&&next.accounts.some(other=>other.id!==a.id&&other.profile.email===changes.email))throw new Error('This email already belongs to another local account.');a.profile={...a.profile,...changes};});mutate(()=>{},'Profile updated','Researcher profile');};
 const requestReset=(email:string)=>{const token=crypto.randomUUID();transact(next=>{const a=next.accounts.find(a=>a.profile.email===email.trim().toLowerCase());if(!a)throw new Error('No local account matches this email.');a.reset={token,expires:Date.now()+900000};});return token;};
 const resetPassword=async(email:string,token:string,password:string)=>{validatePassword(password);const salt=crypto.randomUUID(),passwordHash=await hashPassword(password,salt);transact(next=>{const a=next.accounts.find(a=>a.profile.email===email.trim().toLowerCase());if(!a?.reset||a.reset.token!==token||a.reset.expires<Date.now())throw new Error('This local reset link is invalid or expired.');a.salt=salt;a.passwordHash=passwordHash;delete a.reset;next.session=null;});};
 const startDemo=async()=>{const existing=repository.read().accounts.find(a=>a.demo);if(existing){transact(next=>{next.session=existing.id;});return;}await signup('Demo Researcher',`demo-${crypto.randomUUID()}@arpis.local`,`${crypto.randomUUID()}1`);transact(next=>{const a=next.accounts.find(a=>a.id===next.session)!;a.demo=true;a.profile.onboarded=true;const w=next.workspaces[a.id],now=new Date().toISOString();[['Efficient Retrieval for Scientific Literature','Computer Science'],['Quantum Materials Simulation','Physics'],['Urban Heat Island Analysis','Climate Science'],['Protein Structure Prediction','Biology']].forEach(([name,domain],i)=>{const id=crypto.randomUUID();w.projects.push({id,name,domain,description:'DEMO — an editable example workspace. No analyses or experiments have been executed.',tags:['DEMO'],status:'ACTIVE',icon:'◇',color:['#29f4ff','#a855ff','#ffb74d','#52d273'][i],createdAt:now,updatedAt:now,papers:0,notes:0,chats:0,comparisons:0,progress:0});w.records.push({id:crypto.randomUUID(),kind:'questions',projectId:id,title:`Which methods are most appropriate for ${domain.toLowerCase()}?`,description:'DEMO research question — replace with your own scope.',status:'OPEN',priority:'Medium',tags:['DEMO'],createdAt:now,updatedAt:now});});});};
 const account=db.accounts.find(a=>a.id===db.session),workspace=(db.session&&db.workspaces[db.session])||emptyWorkspace();
 useEffect(()=>{const apply=()=>{document.documentElement.dataset.theme=workspace.settings.theme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):workspace.settings.theme;document.documentElement.dataset.density=workspace.settings.density;};apply();const media=matchMedia('(prefers-color-scheme: light)');media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);},[workspace.settings.theme,workspace.settings.density]);
 return <Context.Provider value={{db,workspace,account,ready,error,notice,dismiss:()=>setNotice(''),transact,mutate,signup,login,logout,updateProfile,startDemo,resetPassword,requestReset}}>{children}</Context.Provider>;
}
export function useWorkspace(){const value=useContext(Context);if(!value)throw new Error('WorkspaceProvider is required');return value;}
