import { test,expect,Page } from '@playwright/test';
async function signup(page:Page){await page.goto('/signup');await page.getByLabel('Full name').fill('Ada Researcher');await page.getByLabel('Email',{exact:true}).fill('ada@example.test');await page.getByLabel('Password',{exact:true}).fill('Research12345');await page.getByLabel('Confirm password').fill('Research12345');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page).toHaveURL(/onboarding/);await page.getByRole('button',{name:'Skip for now'}).click();await expect(page).toHaveURL(/dashboard/);}
async function project(page:Page){await page.goto('/research/new');await page.getByLabel('Project title').fill('Urban cooling study');await page.getByLabel('Description',{exact:true}).fill('Compare urban canopy and temperature observations.');await page.getByRole('combobox',{name:'Research domain',exact:true}).selectOption('Climate Science');await page.getByLabel('Research questions (one per line)').fill('Does canopy reduce local temperature?');await page.getByRole('button',{name:'Create project',exact:true}).click();await expect(page).toHaveURL(/projects\/[^/]+$/);return page.url().split('/').at(-1)!;}
test('complete local researcher journey, research records, export, import, account isolation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await signup(page);const id=await project(page);
 await page.goto(`/papers/new?project=${id}`);await page.getByLabel('Title',{exact:true}).fill('Canopy and surface temperature');await page.getByLabel('Authors (comma separated)').fill('A. Researcher, B. Scientist');await page.getByLabel('Year',{exact:true}).fill('2024');await page.getByLabel('Abstract',{exact:true}).fill('Observations of temperature beneath tree cover.');await page.getByRole('button',{name:'Save source',exact:true}).click();await expect(page.getByRole('heading',{name:'Canopy and surface temperature',exact:true})).toBeVisible();const paper=page.url().split('/').at(-1)!;
 await page.goto(`/evidence/new?project=${id}&paper=${paper}`);await page.getByLabel('Claim',{exact:true}).fill('Tree cover and lower temperature were associated');await page.getByLabel('Evidence text (from source)').fill('Recorded temperature was 293.2 K.');await page.getByLabel('Page / section').fill('Section 3');await page.getByRole('button',{name:'Save evidence item',exact:true}).click();await expect(page.getByRole('heading',{name:'Evidence',exact:true})).toBeVisible();
 await page.goto(`/notes/new?project=${id}&paper=${paper}`);await page.getByLabel('Title',{exact:true}).fill('Confounding factors');await page.getByLabel('Researcher note',{exact:true}).fill('Consider time of day and sensor calibration.');await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByRole('link',{name:'Confounding factors',exact:true})).toBeVisible();
 await page.goto(`/datasets/new?project=${id}`);await page.getByLabel('Title',{exact:true}).fill('Canopy observations');await page.getByLabel('Version',{exact:true}).fill('1.0');await page.getByLabel('Schema / variables / features (one per line)').fill('temperature: number\ncanopy_cover: percent');await page.getByRole('button',{name:'Save dataset',exact:true}).click();await expect(page.getByRole('link',{name:'Canopy observations',exact:true})).toBeVisible();
 await page.goto(`/experiments/new?project=${id}`);await page.getByLabel('Title',{exact:true}).fill('Temperature comparison');await page.getByRole('combobox',{name:'Dataset',exact:true}).selectOption({label:'Canopy observations'});await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('COMPLETED');await page.getByRole('button',{name:'Add measurement'}).click();await page.getByLabel('Metric name',{exact:true}).fill('Temperature');await page.getByLabel('Value',{exact:true}).fill('293.2');await page.getByLabel('Unit',{exact:true}).fill('K');await page.getByRole('button',{name:'Save experiment',exact:true}).click();await expect(page.getByText('Temperature: 293.2 K')).toBeVisible();
 await page.goto('/search?q=Confounding');await expect(page.getByRole('link',{name:'Confounding factors',exact:true})).toBeVisible();
 await page.goto('/profile');await page.getByLabel('Institution',{exact:true}).fill('Independent Research Lab');await page.getByRole('button',{name:'Save profile',exact:true}).click();await page.reload();await expect(page.getByLabel('Institution',{exact:true})).toHaveValue('Independent Research Lab');
 await page.goto('/settings');const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Export research JSON'}).click();const download=await downloaded;const path=await download.path();expect(path).toBeTruthy();await page.getByLabel('Import ARPIS JSON').setInputFiles(path!);await expect(page.getByRole('heading',{name:/Review import/})).toBeVisible();await page.getByRole('button',{name:'Merge',exact:true}).click();
 await page.goto('/dashboard');await expect(page.getByRole('link',{name:/Active projects/})).toContainText('1');await page.getByRole('button',{name:'Log out',exact:true}).click();await expect(page).toHaveURL(/login/);await page.getByLabel('Email',{exact:true}).fill('ada@example.test');await page.getByLabel('Password',{exact:true}).fill('Research12345');await page.getByRole('button',{name:'Log in',exact:true}).click();await expect(page).toHaveURL(/dashboard/);await page.reload();await expect(page.getByRole('heading',{name:'Welcome, Ada.'})).toBeVisible();await expect(page.getByRole('link',{name:/Urban cooling study/})).toBeVisible();
 await page.getByRole('button',{name:'Log out',exact:true}).click();await page.goto('/signup');await page.getByLabel('Full name').fill('Another Researcher');await page.getByLabel('Email',{exact:true}).fill('other@example.test');await page.getByLabel('Password',{exact:true}).fill('Different12345');await page.getByLabel('Confirm password').fill('Different12345');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page).toHaveURL(/onboarding/);await page.getByRole('button',{name:'Skip for now'}).click();await expect(page.getByRole('link',{name:/Active projects/})).toContainText('0');expect(errors).toEqual([]);
});
test('validation, reset, responsive navigation, import error and empty states',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/signup');await page.getByLabel('Full name').fill('Ada Researcher');await page.getByLabel('Email',{exact:true}).fill('ada@example.test');await page.getByLabel('Password',{exact:true}).fill('Research12345');await page.getByLabel('Confirm password').fill('Mismatch12345');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Passwords do not match'})).toBeVisible();await page.getByLabel('Confirm password').fill('Research12345');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page).toHaveURL(/onboarding/);await page.getByRole('button',{name:'Skip for now'}).click();await expect(page.getByRole('heading',{name:'Your next discovery starts here.'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:'Log out',exact:true}).click();await page.goto('/forgot-password');await page.getByLabel('Email',{exact:true}).fill('ada@example.test');await page.getByRole('button',{name:'Create local reset link'}).click();await page.getByRole('link',{name:'Reset password',exact:true}).click();await page.getByLabel('Password',{exact:true}).fill('NewPassword123');await page.getByLabel('Confirm password').fill('NewPassword123');await page.getByRole('button',{name:'Update password',exact:true}).click();await expect(page.getByText('Password updated.',{exact:false})).toBeVisible();await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('ada@example.test');await page.getByLabel('Password',{exact:true}).fill('NewPassword123');await page.getByRole('button',{name:'Log in',exact:true}).click();await expect(page).toHaveURL(/dashboard/);await page.goto('/settings');await page.getByLabel('Import ARPIS JSON').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":2,"workspace":{}}')});await expect(page.getByRole('alert').filter({hasText:'Invalid projects'})).toBeVisible();
});
test('AI provider contract, streamed response persistence and error retry (test provider fixture)',async({page})=>{
 await signup(page);await page.goto('/assistant');await page.evaluate(()=>{(window as unknown as {puter:unknown}).puter={auth:{isSignedIn:()=>true,signIn:async()=>{}},ai:{chat:async()=>{async function* stream(){yield {text:'Test-only provider response. '};yield {text:'Verify source evidence.'};}return stream();}}};});await page.getByRole('button',{name:'Load AI provider',exact:true}).click();await page.getByLabel('Message ARPIS',{exact:true}).fill('Help structure a literature review.');await page.getByRole('button',{name:'Send message',exact:true}).click();await expect(page.getByText('Test-only provider response. Verify source evidence.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Help structure a literature review.',exact:true})).toBeVisible();await page.getByRole('button',{name:'Help structure a literature review.',exact:true}).click();await expect(page.getByText('Test-only provider response. Verify source evidence.',{exact:true})).toBeVisible();await page.evaluate(()=>{(window as unknown as {puter:unknown}).puter={auth:{isSignedIn:()=>true,signIn:async()=>{}},ai:{chat:async()=>{throw new Error('Test provider unavailable');}}};});await page.getByRole('button',{name:'Load AI provider',exact:true}).click();await page.getByLabel('Message ARPIS',{exact:true}).fill('Try another request.');await page.getByRole('button',{name:'Send message',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Test provider unavailable'})).toBeVisible();await expect(page.getByRole('button',{name:'Retry last question',exact:true})).toBeVisible();
});

