"use client";
import Link from 'next/link';
import { useRouter,useSearchParams } from 'next/navigation';
import { FormEvent,useState } from 'react';
import { useWorkspace } from '@/store/WorkspaceProvider';
export default function Auth({mode}:{mode:string}){
 const store=useWorkspace(),router=useRouter(),params=useSearchParams();const [error,setError]=useState(''),[busy,setBusy]=useState(false),[resetLink,setResetLink]=useState(''),[success,setSuccess]=useState('');
 const title:Record<string,string>={login:'Welcome back',signup:'Create your researcher account','forgot-password':'Reset your password','reset-password':'Choose a new password','verify-email':'Email verification demo'};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget),get=(k:string)=>String(f.get(k)||'');try{if(['signup','reset-password'].includes(mode)&&get('password')!==get('confirm'))throw new Error('Passwords do not match.');if(mode==='signup'){await store.signup(get('name'),get('email'),get('password'));router.push('/onboarding');}else if(mode==='login'){await store.login(get('email'),get('password'));router.push('/dashboard');}else if(mode==='forgot-password'){const token=store.requestReset(get('email'));setResetLink(`/reset-password?email=${encodeURIComponent(get('email'))}&token=${token}`);}else if(mode==='reset-password'){await store.resetPassword(params.get('email')||'',params.get('token')||'',get('password'));setSuccess('Password updated. You can now log in.');}else{store.updateProfile({verified:true});setSuccess('Email marked verified for this local demo. No email ownership was verified.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <main className="auth panel"><span className="eyebrow">ARPIS · Research OS</span><h1>{title[mode]}</h1><p>{mode==='signup'?'A focused home for your questions, sources, and discoveries.':'Continue your research across every discipline.'}</p><p className="notice">Local demo accounts only. This is not secure authentication. No emails are sent. Use a demo password you do not use elsewhere.</p><form onSubmit={submit}>{mode==='signup'&&<label>Full name<input name="name" autoComplete="name" required maxLength={100}/></label>}{['signup','login','forgot-password'].includes(mode)&&<label>Email<input name="email" type="email" autoComplete="email" required/></label>}{['signup','login','reset-password'].includes(mode)&&<label>Password<input aria-label="Password" name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:10}/>{mode!=='login'&&<small>At least 10 characters, with a letter and a number.</small>}</label>}{['signup','reset-password'].includes(mode)&&<label>Confirm password<input name="confirm" type="password" autoComplete="new-password" required/></label>}{error&&<p className="alert" role="alert">{error}</p>}{success&&<p role="status">{success} <Link href="/login">Log in</Link></p>}{mode==='verify-email'&&!store.account?<Link href="/login">Log in to verify your local demo account</Link>:<button className="primary" disabled={busy||!store.ready}>{busy?'Please wait…':mode==='login'?'Log in':mode==='signup'?'Create account':mode==='forgot-password'?'Create local reset link':mode==='verify-email'?'Mark verified (demo)':'Update password'}</button>}</form>{resetLink&&<p role="status">No email was sent. This local link expires in 15 minutes: <Link className="button" href={resetLink}>Reset password</Link></p>}<div className="row" style={{marginTop:22}}>{mode==='login'?<><Link href="/signup">Create account</Link><Link href="/forgot-password">Forgot password?</Link></>:<Link href="/login">Back to login</Link>}</div></main>;
}

