"use client";
import Link from 'next/link';
import { useRouter,useSearchParams } from 'next/navigation';
import { FormEvent,useState } from 'react';
import { Paper } from '@/lib/papers';
import { domains } from '@/lib/research-model';
import { useWorkspace } from '@/store/WorkspaceProvider';
import { usePapers } from '@/components/papers/PaperProvider';
import { savePdf } from '@/lib/pdfStore';
const types=['journal paper','conference paper','preprint','book','thesis','technical report','dataset','website','documentation','other'];
export function safeUrl(value?:string){try{const u=new URL(value||'');return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export default function Papers({id,projectId}:{id?:string;projectId?:string}){
 const {workspace:w}=useWorkspace(),{updatePaper,deletePaper}=usePapers(),params=useSearchParams(),router=useRouter();const [query,setQuery]=useState(''),[filter,setFilter]=useState('active'),[sort,setSort]=useState('recent'),[editing,setEditing]=useState(false),[domain,setDomain]=useState('');const scope=projectId||params.get('project')||'';const paper=w.papers.find(p=>p.id===id&&(!scope||p.projectId===scope));
 if(id==='new'||paper&&editing)return <main className="page"><h1>{paper?'Edit source':'Add a paper or source'}</h1><p>Save metadata, attach a PDF, and connect the source to your project.</p><PaperEditor paper={paper} projectId={scope} onDone={()=>setEditing(false)}/></main>;
 if(id&&!paper)return <main className="page"><h1>Source not found</h1><Link href="/papers">Return to library</Link></main>;
 if(paper){const notes=w.records.filter(r=>r.paperId===paper.id&&r.kind==='notes'),evidence=w.records.filter(r=>r.paperId===paper.id&&r.kind==='evidence');return <main className="page"><Link href={`/projects/${paper.projectId}/papers`}>← Project library</Link><header><span className="eyebrow">SOURCE · {paper.sourceType||'journal paper'}</span><h1>{paper.title}</h1><p>{paper.authors.join(', ')||'Authors not recorded'} · {paper.year||'Year not recorded'} · {paper.journal}</p><div className="row">{paper.tags.map(t=><span className="badge" key={t}>{t}</span>)}</div></header><div className="row"><button className="primary" onClick={()=>setEditing(true)}>Edit metadata</button><button onClick={()=>updatePaper(paper.id,{favorite:!paper.favorite})}>{paper.favorite?'★ Favorited':'☆ Favorite'}</button><button onClick={()=>updatePaper(paper.id,{archived:!paper.archived})}>{paper.archived?'Unarchive':'Archive'}</button>{safeUrl(paper.url)&&<a className="button" href={safeUrl(paper.url)} target="_blank" rel="noreferrer">Open source ↗</a>}<Link className="button" href={`/projects/${paper.projectId}/papers/${paper.id}/reader`}>PDF reader</Link><Link className="button" href={`/assistant?project=${paper.projectId}&paper=${paper.id}`}>Ask ARPIS about this paper</Link></div><div className="stack" style={{marginTop:25}}><section className="panel"><h2>Abstract</h2><p>{paper.abstract||'No abstract recorded.'}</p>{paper.doi&&<p>DOI: <a href={`https://doi.org/${encodeURIComponent(paper.doi)}`} target="_blank" rel="noreferrer">{paper.doi}</a></p>}<p>{paper.notes}</p></section><section className="panel"><h2>Citation · {w.settings? 'Source metadata':''}</h2><p>{paper.authors.join(', ')} ({paper.year}). {paper.title}. {paper.journal}. {paper.doi?`https://doi.org/${paper.doi}`:paper.url}</p><small>Metadata citation; check formatting against your publication requirements.</small></section>{[['Researcher notes',notes,'notes'],['Evidence',evidence,'evidence']].map(([title,items,kind])=><section className="panel" key={String(kind)}><div className="row between"><h2>{String(title)}</h2><Link className="button" href={`/${kind}/new?project=${paper.projectId}&paper=${paper.id}`}>+ Add {kind==='notes'?'note':'evidence'}</Link></div>{(items as typeof notes).length?(items as typeof notes).map(n=><div className="record-row" key={n.id}><Link href={`/${kind}/${n.id}`}>{n.title}</Link><p>{n.content}</p></div>):<p>No {String(title).toLowerCase()} linked yet.</p>}</section>)}<section className="panel"><h2>Related project items</h2>{w.records.filter(r=>r.linkedPaperIds?.includes(paper.id)).map(r=><p key={r.id}><Link href={`/${r.kind}/${r.id}`}>{r.title}</Link></p>)}<Link href={`/projects/${paper.projectId}`}>Open project workspace →</Link></section><button className="danger" onClick={()=>{if(confirm('Remove this source and its saved PDF? Notes are retained with their source link cleared.')){deletePaper(paper.id);router.push('/papers');}}}>Remove source</button></div></main>;}
 const papers=w.papers.filter(p=>(!scope||p.projectId===scope)&&(!domain||p.domain===domain)&&(filter==='all'||filter==='favorites'?filter!=='favorites'||p.favorite:filter==='archived'?p.archived:!p.archived)&&`${p.title} ${p.authors.join(' ')} ${p.abstract} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='year'?b.year-a.year:b.uploadedAt.localeCompare(a.uploadedAt));
 return <section className={projectId?'':'page'}><header className="row between"><div><span className="eyebrow">Source library</span><h1>Papers & sources</h1><p>Build a literature collection across disciplines and source types.</p></div><Link className="button primary" href={`/papers/new${scope?`?project=${scope}`:''}`}>+ Add source</Link></header><div className="toolbar"><input aria-label="Search sources" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, author, abstract, tags…"/><select aria-label="Library filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active sources</option><option value="all">All sources</option><option value="favorites">Favorites</option><option value="archived">Archived</option></select><select aria-label="Source domain" value={domain} onChange={e=>setDomain(e.target.value)}><option value="">All domains</option>{domains.map(d=><option key={d}>{d}</option>)}</select><select aria-label="Sort sources" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recently added</option><option value="title">Title A–Z</option><option value="year">Year (newest)</option></select></div>{papers.length?<section className="panel">{papers.map(p=><article className="record-row" key={p.id}><div className="row between"><div><span className="eyebrow">{p.sourceType||'paper'} · {p.year}</span><h2><Link href={`/papers/${p.id}`}>{p.title}</Link></h2><small>{p.authors.join(', ')} · {p.journal} · {p.status}</small></div><button aria-label={`Favorite ${p.title}`} aria-pressed={p.favorite} onClick={()=>updatePaper(p.id,{favorite:!p.favorite})}>{p.favorite?'★':'☆'}</button></div></article>)}</section>:<div className="empty"><h2>No sources in this view.</h2><p>Add a paper, preprint, book, report, or other source.</p><Link className="button" href={`/papers/new${scope?`?project=${scope}`:''}`}>Add your first source</Link></div>}</section>;
}
function PaperEditor({paper,projectId,onDone}:{paper?:Paper;projectId:string;onDone:()=>void}){
 const {workspace:w}=useWorkspace(),{addPaper,updatePaper}=usePapers(),router=useRouter();const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget),get=(k:string)=>String(f.get(k)||'').trim(),list=(k:string)=>get(k).split(',').map(v=>v.trim()).filter(Boolean);try{if(!get('title')||!get('projectId'))throw new Error('Enter a title and select a project.');if(get('url')&&!safeUrl(get('url')))throw new Error('Enter an HTTP or HTTPS source URL.');if(file&&(!file.name.toLowerCase().endsWith('.pdf')||file.size>30*1024*1024))throw new Error('Choose a PDF under 30 MB.');const record:Paper={...paper,id:paper?.id||crypto.randomUUID(),projectId:get('projectId'),title:get('title'),authors:list('authors'),year:Number(get('year'))||0,abstract:get('abstract'),keywords:list('keywords'),journal:get('journal'),pages:Number(get('pages'))||0,uploadedAt:paper?.uploadedAt||new Date().toISOString(),status:get('status') as Paper['status'],tags:list('tags'),favorite:paper?.favorite||false,doi:get('doi'),url:get('url'),domain:get('domain'),sourceType:get('sourceType'),notes:get('notes'),fileName:file?.name||paper?.fileName};if(file)await savePdf(record.id,file);if(paper)updatePaper(record.id,record);else addPaper(record);onDone();router.push(`/papers/${record.id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <form className="panel" onSubmit={save}><div className="form-grid"><label>Project<select name="projectId" defaultValue={paper?.projectId||projectId} required><option value="">Select a project</option>{w.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{!w.projects.length&&<Link href="/research/new">Create a project first</Link>}</label><label>Source type<select name="sourceType" defaultValue={paper?.sourceType||types[0]}>{types.map(t=><option key={t}>{t}</option>)}</select></label>{(['title','authors','year','journal','doi','url','tags','keywords','pages'] as const).map(k=><label className={k==='title'?'full':''} key={k}>{({title:'Title',authors:'Authors (comma separated)',year:'Year',journal:'Journal / conference / publisher',doi:'DOI',url:'Source URL',tags:'Tags (comma separated)',keywords:'Keywords (comma separated)',pages:'Pages'})[k]}<input name={k} required={k==='title'} type={k==='year'||k==='pages'?'number':k==='url'?'url':'text'} min={k==='year'?1000:0} max={k==='year'?new Date().getFullYear()+1:undefined} defaultValue={Array.isArray(paper?.[k])?(paper?.[k] as string[]).join(', '):String(paper?.[k]||'')}/></label>)}<label>Research domain<select name="domain" defaultValue={paper?.domain||domains[0]}>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label>Reading status<select name="status" defaultValue={paper?.status||'Unread'}>{['Unread','Reading','Completed','Reviewed'].map(s=><option key={s}>{s}</option>)}</select></label><label className="full">Abstract<textarea name="abstract" rows={6} defaultValue={paper?.abstract}/></label><label className="full">Metadata notes<textarea name="notes" defaultValue={paper?.notes}/></label><label className="full">Optional PDF (saved in this browser)<input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>Up to 30 MB. No text extraction or analysis is performed.</small></label></div>{error&&<p className="alert" role="alert">{error}</p>}<div className="row"><button disabled={busy} className="primary">{busy?'Saving source…':'Save source'}</button><Link href="/papers">Cancel</Link><Link href="/fetch">Import metadata by DOI / arXiv →</Link></div></form>;
}
