"use client";
import Link from 'next/link';
import { FormEvent,useState } from 'react';
import { domains,Profile as ProfileType } from '@/lib/research-model';
import { useWorkspace } from '@/store/WorkspaceProvider';
import { safeUrl } from './Papers';
export default function Profile(){const {account,updateProfile}=useWorkspace();const [error,setError]=useState(''),[avatar,setAvatar]=useState(account?.profile.avatar||'');if(!account)return null;const p=account.profile;
 const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),get=(k:string)=>String(f.get(k)||'').trim();try{if(!get('name')||!/^\S+@\S+\.\S+$/.test(get('email')))throw new Error('Enter your name and a valid email.');if(get('website')&&!safeUrl(get('website')))throw new Error('Enter an HTTP or HTTPS website URL.');if(get('orcid')&&!/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/.test(get('orcid')))throw new Error('ORCID format: 0000-0000-0000-0000.');const changes:Partial<ProfileType>={avatar,domains:f.getAll('domains').map(String)};for(const k of ['name','email','institution','interests','bio','orcid','website','location','citation','language'] as const)changes[k]=get(k);changes.email=changes.email?.toLowerCase();if(changes.email!==p.email)changes.verified=false;updateProfile(changes);setError('');}catch(e){setError((e as Error).message);}};
 return <main className="page" style={{maxWidth:1000}}><header><span className="eyebrow">Researcher profile</span><h1>Your research identity</h1><p>Share as much or as little as you want. This profile stays on this device.</p></header><form className="panel" onSubmit={save}><div className="row">{avatar?<img src={avatar} className="avatar" alt="Profile avatar" width={60} height={60}/>:<div className="avatar">{p.name[0]}</div>}<label>Profile photo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>300000){setError('Choose a PNG, JPEG, or WebP smaller than 300 KB.');return;}const reader=new FileReader();reader.onload=()=>setAvatar(String(reader.result));reader.onerror=()=>setError('Could not read image.');reader.readAsDataURL(file);}}/></label>{avatar&&<button type="button" onClick={()=>setAvatar('')}>Remove photo</button>}</div><div className="form-grid">{(['name','email','institution','interests','orcid','website','location'] as const).map(k=><label key={k}>{({name:'Full name',email:'Email',institution:'Institution',interests:'Research interests',orcid:'ORCID',website:'Website',location:'Location'})[k]}<input name={k} type={k==='email'?'email':k==='website'?'url':'text'} required={k==='name'||k==='email'} defaultValue={p[k]}/></label>)}<label>Preferred citation style<select name="citation" defaultValue={p.citation}>{['APA','MLA','Chicago','IEEE','Vancouver','Harvard'].map(s=><option key={s}>{s}</option>)}</select></label><label>Preferred language<input name="language" defaultValue={p.language}/></label><label className="full">Short bio<textarea name="bio" defaultValue={p.bio} maxLength={1500}/></label><fieldset className="full"><legend>Research domains</legend><div className="grid">{domains.map(d=><label className="check" key={d}><input type="checkbox" name="domains" value={d} defaultChecked={p.domains.includes(d)}/>{d}</label>)}</div></fieldset></div>{error&&<p role="alert" className="alert">{error}</p>}<div className="row" style={{marginTop:20}}><button className="primary">Save profile</button><Link href="/verify-email">{p.verified?'Email marked verified (demo)':'Verify email (demo)'}</Link></div></form></main>;
}
