"use client";
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent,useState } from 'react';
import { domains } from '@/lib/research-model';
import { useWorkspace } from '@/store/WorkspaceProvider';
export function ProjectForm({id,onDone}:{id?:string;onDone?:()=>void}){
 const {workspace,mutate}=useWorkspace(),router=useRouter(),project=workspace.projects.find(p=>p.id===id);const [error,setError]=useState('');
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),get=(k:string)=>String(f.get(k)||'').trim(),now=new Date().toISOString(),projectId=id||crypto.randomUUID();try{if(!get('name'))throw new Error('A project title is required.');mutate(w=>{const p={id:projectId,name:get('name'),description:get('description'),domain:get('domain'),tags:get('tags').split(',').map(t=>t.trim()).filter(Boolean),status:get('status') as 'ACTIVE',icon:project?.icon||'◇',color:project?.color||'#29f4ff',createdAt:project?.createdAt||now,updatedAt:now,papers:project?.papers||0,notes:0,chats:0,comparisons:0,progress:0};w.projects=[p,...w.projects.filter(p=>p.id!==projectId)];if(!id){for(const title of get('questions').split('\n').filter(Boolean))w.records.push({id:crypto.randomUUID(),kind:'questions',projectId,title,description:'',status:'OPEN',priority:'Medium',tags:[],createdAt:now,updatedAt:now});if(get('hypothesis'))w.records.push({id:crypto.randomUUID(),kind:'hypotheses',projectId,title:get('hypothesis'),description:'',status:'PROPOSED',tags:[],createdAt:now,updatedAt:now});}},id?'Project updated':'Project created',get('name'),projectId,`/projects/${projectId}`);if(onDone)onDone();else router.push(`/projects/${projectId}`);}catch(e){setError((e as Error).message);}};
 return <form className="panel" onSubmit={submit}><div className="form-grid"><label className="full">Project title<input name="name" required maxLength={160} defaultValue={project?.name}/></label><label className="full">Description<textarea name="description" defaultValue={project?.description} rows={3}/></label><label>Research domain<select name="domain" defaultValue={project?.domain||workspace.settings.domain||domains[0]}>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label>Status<select name="status" defaultValue={project?.status||'ACTIVE'}>{['ACTIVE','PAUSED','COMPLETED','ARCHIVED'].map(s=><option key={s}>{s}</option>)}</select></label><label className="full">Tags (comma separated)<input name="tags" defaultValue={project?.tags.join(', ')}/></label>{!id&&<><label className="full">Research questions (one per line)<textarea name="questions" placeholder="What are you trying to understand?"/></label><label className="full">Initial hypothesis (optional)<textarea name="hypothesis"/></label></>}</div>{error&&<p role="alert" className="alert">{error}</p>}<div className="row"><button className="primary">{id?'Save project':'Create project'}</button><Link href={id?`/projects/${id}`:'/research'}>Cancel</Link></div></form>;
}
export default function Projects(){const {workspace,mutate}=useWorkspace();const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[sort,setSort]=useState('updated');const projects=workspace.projects.filter(p=>`${p.name} ${p.domain} ${p.description} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())&&(!status||(p.status||'ACTIVE')===status)).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):b.updatedAt.localeCompare(a.updatedAt));
 return <main className="page"><header className="row between"><div><span className="eyebrow">My Research</span><h1>Your projects</h1><p>Every question deserves a focused workspace.</p></div><Link href="/research/new" className="button primary">+ New project</Link></header><div className="toolbar"><input aria-label="Search projects" placeholder="Search projects, domains, tags…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter project status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['ACTIVE','PAUSED','COMPLETED','ARCHIVED'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Sort projects" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">Recently updated</option><option value="name">Title A–Z</option></select></div>{projects.length?<div className="grid">{projects.map(p=><article className="panel" key={p.id}><div className="row between"><span className="eyebrow">{p.domain}</span><span className="badge">{p.status||'ACTIVE'}</span></div><h2><Link href={`/projects/${p.id}`}>{p.name}</Link></h2><p>{p.description||'Add a description to frame this research.'}</p><small>{workspace.papers.filter(x=>x.projectId===p.id).length} papers · {workspace.records.filter(x=>x.projectId===p.id&&x.kind==='notes').length} notes · Updated {new Date(p.updatedAt).toLocaleDateString()}</small><div className="row" style={{marginTop:20}}><Link className="button" href={`/projects/${p.id}`}>Open workspace →</Link><button onClick={()=>{const now=new Date().toISOString(),id=crypto.randomUUID();mutate(w=>{w.projects.unshift({...p,id,name:`${p.name} (copy)`,createdAt:now,updatedAt:now});const mapping=new Map([...w.papers,...w.records,...w.conversations].filter(r=>r.projectId===p.id).map(r=>[r.id,crypto.randomUUID()]));const remap=(ids?:string[])=>ids?.map(id=>mapping.get(id)||id);w.papers.push(...w.papers.filter(r=>r.projectId===p.id).map(r=>({...r,id:mapping.get(r.id)!,projectId:id,fileName:undefined})));w.records.push(...w.records.filter(r=>r.projectId===p.id).map(r=>({...r,id:mapping.get(r.id)!,projectId:id,paperId:mapping.get(r.paperId||''),experimentId:mapping.get(r.experimentId||''),datasetId:mapping.get(r.datasetId||''),hypothesisId:mapping.get(r.hypothesisId||''),linkedPaperIds:remap(r.linkedPaperIds),linkedNoteIds:remap(r.linkedNoteIds),linkedExperimentIds:remap(r.linkedExperimentIds),linkedEvidenceIds:remap(r.linkedEvidenceIds)})));w.conversations.push(...w.conversations.filter(r=>r.projectId===p.id).map(r=>({...r,id:mapping.get(r.id)!,projectId:id})));},'Project duplicated',p.name,id,`/projects/${id}`);}}>Duplicate</button></div></article>)}</div>:<div className="empty"><h2>{workspace.projects.length?'No matching projects':'Start with a question'}</h2><p>Create a project to bring your sources and thinking together.</p><Link className="button primary" href="/research/new">Create project</Link></div>}</main>;
}
