"use client";
import Link from 'next/link';
import { usePathname,useRouter } from 'next/navigation';
import { useEffect,useState } from 'react';
import { useWorkspace } from '@/store/WorkspaceProvider';
const nav=[['Dashboard','/dashboard'],['My Research','/research'],['Papers','/papers'],['Datasets','/datasets'],['Experiments','/experiments'],['Notes','/notes'],['AI Research Assistant','/assistant'],['Activity','/activity'],['Settings','/settings']];
const publicRoutes=['/','/login','/signup','/forgot-password','/reset-password','/verify-email'];
export default function Shell({children}:{children:React.ReactNode}){
 const {account,ready,error,notice,dismiss,logout,workspace}=useWorkspace();const path=usePathname(),router=useRouter();const [open,setOpen]=useState(false);const isPublic=publicRoutes.includes(path);
 useEffect(()=>{if(ready&&!account&&!isPublic)router.replace('/login');else if(ready&&account&&!account.profile.onboarded&&!isPublic&&path!=='/onboarding')router.replace('/onboarding');},[ready,account,isPublic,path,router]);
 useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[open]);
 const messages=<>{error&&<div role="alert" className="alert">{error}</div>}{notice&&<div role="status" className="toast">{notice} <button onClick={dismiss} aria-label="Dismiss notification">×</button></div>}</>;
 if(isPublic)return <div className="os"><nav className="public-nav"><Link href="/" className="brand">ARP<span>IS</span></Link><div className="row"><Link href={account?'/dashboard':'/login'}>{account?'Dashboard':'Log in'}</Link><Link className="button primary" href="/signup">Start Researching</Link></div></nav>{messages}{children}</div>;
 if(!ready||!account)return <div className="os"><main className="page"><p role="status">Loading your workspace…</p>{messages}</main></div>;
 return <div className="os"><a className="skip" href="#main-content">Skip to content</a><div className="shell"><aside className={`sidebar ${open?'open':''}`} aria-label="Main navigation"><div className="row between"><Link className="brand" href="/dashboard">ARP<span>IS</span></Link><button className="mobile-toggle" onClick={()=>setOpen(false)} aria-label="Close navigation">×</button></div><nav>{nav.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)} aria-current={path.startsWith(href)?'page':undefined}>{label}</Link>)}</nav><footer><span className="badge">{account.demo?'DEMO WORKSPACE':'LOCAL WORKSPACE'}</span><p>Research, connected.</p><button onClick={()=>{logout();router.push('/login');}}>Log out</button></footer></aside><div><header className="topbar"><button className="mobile-toggle" aria-expanded={open} aria-label="Open navigation" onClick={()=>setOpen(!open)}>☰</button><form action="/search"><label className="sr-only" htmlFor="global-search">Search all research</label><input id="global-search" name="q" placeholder="Search your research…"/></form><select aria-label="Current project" value={path.startsWith('/projects/')?path.split('/')[2]:''} onChange={e=>e.target.value&&router.push(`/projects/${e.target.value}`)}><option value="">Open a project</option>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Link href="/notifications" aria-label={`Notifications, ${workspace.notifications.filter(n=>!n.read).length} unread`}>Notifications <span className="badge">{workspace.notifications.filter(n=>!n.read).length}</span></Link><Link href="/profile" className="avatar" aria-label="Your profile">{account.profile.name.slice(0,1)}</Link></header><div className="notice">{account.demo?'DEMO · Sample data is editable. ':''}Frontend workspace · Saved in this browser. Export a backup in Settings.</div>{messages}<div id="main-content">{children}</div></div></div><nav className="bottom-nav" aria-label="Mobile shortcuts">{nav.filter((_,i)=>[0,1,2,6].includes(i)).map(([label,href])=><Link key={href} href={href}>{label==='AI Research Assistant'?'Assistant':label}</Link>)}</nav></div>;
}
