"use client";
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { useWorkspace } from '@/store/WorkspaceProvider';
export function Timeline({projectId}:{projectId?:string}){const {workspace}=useWorkspace();const [query,setQuery]=useState('');const events=workspace.activity.filter(a=>(!projectId||a.projectId===projectId)&&`${a.action} ${a.object}`.toLowerCase().includes(query.toLowerCase()));return <section className="panel"><label>Filter activity<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actions and objects…"/></label>{events.length?<ol className="list">{events.map(a=><li key={a.id}><span className="badge">{a.action}</span><strong> {a.object}</strong><br/><small>{new Date(a.createdAt).toLocaleString()}{a.projectId?` · ${workspace.projects.find(p=>p.id===a.projectId)?.name||'Deleted project'}`:''}</small></li>)}</ol>:<p>No activity matches this view.</p>}</section>;}
export function ActivityPage(){return <main className="page"><header><span className="eyebrow">Research history</span><h1>Your research trail</h1><p>Actions recorded as you build and organize your work.</p></header><Timeline/></main>;}
export function Notifications(){const {workspace:w,mutate}=useWorkspace();return <main className="page"><header className="row between"><div><span className="eyebrow">Updates</span><h1>Notifications</h1></div><button onClick={()=>mutate(w=>{w.notifications.forEach(n=>{n.read=true;});})}>Mark all as read</button></header><section className="panel">{w.notifications.length?w.notifications.map(n=><article className="record-row" key={n.id}><div className="row between"><div><span className="badge">{n.read?'Read':'New'}</span> <strong>{n.action}</strong><p>{n.object}</p><small>{new Date(n.createdAt).toLocaleString()}</small></div><div className="row">{!n.read&&<button onClick={()=>mutate(w=>{w.notifications.find(x=>x.id===n.id)!.read=true;})}>Mark as read</button>}<button onClick={()=>mutate(w=>{w.notifications=w.notifications.filter(x=>x.id!==n.id);})}>Clear</button></div></div></article>):<div className="empty"><h2>All caught up.</h2><p>Your research actions will create notifications here.</p></div>}</section></main>;}
export function Search(){const {workspace:w}=useWorkspace(),params=useSearchParams();const [query,setQuery]=useState(params.get('q')||'');const term=query.trim().toLowerCase();const groups=[{name:'Projects',items:w.projects.map(p=>({id:p.id,title:p.name,text:`${p.description} ${p.domain} ${p.tags.join(' ')}`,href:`/projects/${p.id}`}))},{name:'Papers',items:w.papers.map(p=>({id:p.id,title:p.title,text:`${p.abstract} ${p.authors.join(' ')} ${p.tags.join(' ')}`,href:`/papers/${p.id}`}))},...['notes','datasets','experiments','questions','hypotheses','evidence'].map(kind=>({name:kind[0].toUpperCase()+kind.slice(1),items:w.records.filter(r=>r.kind===kind).map(r=>({id:r.id,title:r.title,text:`${r.description} ${r.content||''} ${r.tags.join(' ')}`,href:`/${kind}/${r.id}`}))})),{name:'Conversations',items:w.conversations.map(c=>({id:c.id,title:c.title,text:c.messages.map(m=>m.content).join(' '),href:`/assistant?conversation=${c.id}&project=${c.projectId}`}))}].map(g=>({...g,items:g.items.filter(i=>term&&`${i.title} ${i.text}`.toLowerCase().includes(term))}));return <main className="page"><header><span className="eyebrow">Across your workspace</span><h1>Search your research</h1></header><label>Search<input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="A question, paper, dataset, note, or conversation…"/></label>{groups.some(g=>g.items.length)?groups.filter(g=>g.items.length).map(g=><section className="panel" style={{marginTop:20}} key={g.name}><h2>{g.name} ({g.items.length})</h2>{g.items.map(i=><div className="record-row" key={i.id}><Link href={i.href}><strong>{i.title}</strong></Link><p>{i.text.slice(0,200)}</p></div>)}</section>):<div className="empty"><h2>{term?'No matching research':'Find the connection'}</h2><p>{term?'Try another phrase or add more research to your workspace.':'Search across your projects, sources, notes, experiments, and conversations.'}</p></div>}</main>;}
export function download(name:string,body:string,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
