"use client";
import Link from "next/link";
import { FiArrowUpRight,FiClock,FiFileText,FiFolderPlus,FiPlus,FiStar,FiTrendingUp } from "react-icons/fi";
import { useProjects } from "@/components/projects/ProjectProvider";
import { usePapers } from "@/components/papers/PaperProvider";
import styles from "./page.module.css";

export default function HomePage(){
 const {projects,ready,openCreateProject}=useProjects();
 const {papers}=usePapers();
 const favorites=papers.filter(p=>p.favorite),notes=projects.reduce((sum,p)=>sum+p.notes,0);
 return <main className={styles.dashboard}>
  <header className={styles.hero}><div><p className={styles.eyebrow}>Research workspace</p><h1>Good morning, Cherika.</h1><p>Pick up where you left off or start a new research project.</p></div><button onClick={openCreateProject} className={styles.primaryButton}><FiPlus/> New project</button></header>
  <section className={styles.section}><div className={styles.sectionHeader}><div><h2>Recent projects</h2><p>Every paper, conversation, and insight stays in context.</p></div><Link href="/projects" className={styles.textLink}>View all <FiArrowUpRight/></Link></div><div className={styles.projectGrid}>{ready&&projects.slice(0,3).map(project=><Link href={`/projects/${project.id}`} className={styles.projectCard} key={project.id}><div className={styles.projectIcon} style={{color:project.color,background:`${project.color}1f`}}>{project.icon}</div><div className={styles.projectMeta}><span>{new Date(project.updatedAt).toLocaleDateString()}</span><FiArrowUpRight/></div><h3>{project.name}</h3><p>{papers.filter(p=>p.projectId===project.id).length} papers</p><div className={styles.progress}><span style={{width:`${project.progress}%`}}/></div><small>Research progress {project.progress}%</small></Link>)}<button onClick={openCreateProject} className={`${styles.projectCard} ${styles.newProjectCard}`}><span className={styles.addIcon}><FiPlus/></span><strong>Create a project</strong><p>Give your research a focused home.</p></button></div></section>
  <div className={styles.contentGrid}><section className={styles.panel}><div className={styles.sectionHeader}><div><h2>Workspace activity</h2><p>Your research operating system at a glance</p></div><FiTrendingUp className={styles.panelIcon}/></div><div className={styles.statsGrid}><div><strong>{papers.length}</strong><span>Papers</span><small>Across projects</small></div><div><strong>{projects.length}</strong><span>Projects</span><small>Active workspaces</small></div><div><strong>{notes}</strong><span>Notes</span><small>Connected insights</small></div><div><strong>{projects.reduce((s,p)=>s+p.chats,0)}</strong><span>AI Chats</span><small>In context</small></div></div></section><section className={styles.panel}><div className={styles.sectionHeader}><div><h2>Quick actions</h2><p>Start inside a research context</p></div></div><div className={styles.actions}><button onClick={openCreateProject}><FiFolderPlus/><span><strong>New project</strong><small>Define a research question</small></span><FiArrowUpRight/></button><Link href={projects[0]?`/projects/${projects[0].id}/papers`:"/projects"}><FiFileText/><span><strong>Paper library</strong><small>Browse project sources</small></span><FiArrowUpRight/></Link><Link href="/history"><FiClock/><span><strong>Recent activity</strong><small>Review your research trail</small></span><FiArrowUpRight/></Link></div></section></div>
  <section className={styles.panel}><div className={styles.sectionHeader}><div><h2>Favorite papers</h2><p>Pinned papers from across your projects</p></div><FiStar className={styles.panelIcon}/></div><div className={styles.paperList}>{favorites.length?favorites.map(paper=><Link className={styles.paperRow} href={`/projects/${paper.projectId}/papers/${paper.id}`} key={paper.id}><span className={styles.fileIcon}><FiFileText/></span><div><strong>{paper.title}</strong><p>{paper.authors.join(", ")} · {paper.year}</p></div><FiArrowUpRight/></Link>):<p>No favorite papers yet. Star a paper to pin it here.</p>}</div></section>
 </main>
}
